import type { GofishDisplayListDocument } from "./gofishIR"
import {
  flowerDisplayList,
  polarribbonDisplayList,
  treemapDisplayList,
  bottleDisplayList,
  pythonDisplayList,
  gofishDisplayListExamples as generatedExamples
} from "./gofishDisplayListFixtures.generated"
import { bobaDisplayList } from "./gofishBobaHandwritten"

/**
 * Canonical GoFish **DisplayList** documents for the adapter gallery.
 *
 * Most are *real* baked render-IR documents — the output of `gofish-graphics`'
 * `toDisplayList({ w, h })` layout pass — generated by
 * `scripts/gen-gofish-fixtures.ts` and checked in so the adapter tests and the
 * `/interoperability/gofish` page stay deterministic and never depend on the
 * GoFish nightly at runtime. Each stands in for what a host gets by calling
 * `await spec.toDisplayList({ w, h })`.
 *
 * The one exception is **boba**, which is *hand-written* (`gofishBobaHandwritten.ts`,
 * no `gofish-graphics` at all) — the counter-proof that the DisplayList is an
 * open, host-emittable format, not something only GoFish can produce.
 *
 * Regenerate the baked set after a GoFish bump with:
 *   `node --experimental-strip-types scripts/gen-gofish-fixtures.ts --write`
 */

// The generated module types its docs against gofish-ir's `DisplayList`
// namespace; the adapter's local `GofishDisplayListDocument` is the same shape,
// so we re-expose them under the adapter's type for callers of the public API.

export const flowerIR = flowerDisplayList as GofishDisplayListDocument
export const polarribbonIR = polarribbonDisplayList as GofishDisplayListDocument
export const treemapIR = treemapDisplayList as GofishDisplayListDocument
export const bottleIR = bottleDisplayList as GofishDisplayListDocument
export const bobaIR = bobaDisplayList
export const pythonIR = pythonDisplayList as GofishDisplayListDocument

export interface GofishIRExample {
  /** Generated keys (derived so new baked fixtures never drift this) plus the hand-written `boba`. */
  key: (typeof generatedExamples)[number]["key"] | "boba"
  label: string
  doc: GofishDisplayListDocument
  /** A one-line note on what the document demonstrates. */
  blurb: string
  /** The upstream example this mirrors. */
  source: string
  /** True for the hand-emitted document (no GoFish bake). */
  handWritten?: boolean
}

const baked: GofishIRExample[] = generatedExamples.map((e) => ({
  key: e.key,
  label: e.label,
  doc: e.doc as GofishDisplayListDocument,
  blurb: e.blurb,
  source: e.source
}))

const bobaExample: GofishIRExample = {
  key: "boba",
  label: "Boba volume cups (hand-written)",
  doc: bobaDisplayList,
  blurb:
    "A pictorial bubble-tea chart written by hand — no gofish-graphics, no GoFish layout solve. Trapezoid cup outlines, lid bars, tilted straws, packed tapioca pearls, tan tea, and ice cubes are all computed in plain arithmetic and emitted as path/ellipse/rect/text items, proving the render IR is an open format any host can produce and still get Semiotic's hit-testing, tooltips, SSR, and a11y. The three volume bands per drink are data nodes; the cup, straw, pearls, and labels are chrome.",
  source: "https://observablehq.com/@kristw/boba-science",
  handWritten: true
}

/** All DisplayList examples, in gallery order — the hand-emitted boba sits among the baked set. */
const bottleIdx = baked.findIndex((e) => e.key === "bottle")
export const gofishIRExamples: readonly GofishIRExample[] = [
  ...baked.slice(0, bottleIdx + 1),
  bobaExample,
  ...baked.slice(bottleIdx + 1)
]
