import type { GofishDisplayListDocument } from "./gofishIR"
import {
  barsDisplayList,
  flowerDisplayList,
  treemapDisplayList,
  bottleDisplayList,
  bobaDisplayList,
  pythonDisplayList,
  gofishDisplayListExamples as generatedExamples,
} from "./gofishDisplayListFixtures.generated"

/**
 * Canonical GoFish **DisplayList** documents for the adapter gallery.
 *
 * These are *real* baked render-IR documents — the output of
 * `gofish-graphics`' `toDisplayList({ w, h })` layout pass — generated by
 * `scripts/gen-gofish-fixtures.ts` and checked in so the adapter tests and the
 * `/interoperability/gofish` page stay deterministic and never depend on the
 * GoFish nightly at runtime. Each stands in for what a host gets by calling
 * `await spec.toDisplayList({ w, h })`.
 *
 * Regenerate after a GoFish bump with:
 *   `node --experimental-strip-types scripts/gen-gofish-fixtures.ts --write`
 */

// The generated module types its docs against gofish-ir's `DisplayList`
// namespace; the adapter's local `GofishDisplayListDocument` is the same shape,
// so we re-expose them under the adapter's type for callers of the public API.
export const barsIR = barsDisplayList as GofishDisplayListDocument
export const flowerIR = flowerDisplayList as GofishDisplayListDocument
export const treemapIR = treemapDisplayList as GofishDisplayListDocument
export const bottleIR = bottleDisplayList as GofishDisplayListDocument
export const bobaIR = bobaDisplayList as GofishDisplayListDocument
export const pythonIR = pythonDisplayList as GofishDisplayListDocument

export interface GofishIRExample {
  key: "bars" | "flower" | "treemap" | "bottle" | "boba" | "python"
  label: string
  doc: GofishDisplayListDocument
  /** A one-line note on what the baked list demonstrates. */
  blurb: string
  /** The upstream GoFish example this mirrors. */
  source: string
}

/** All baked DisplayList examples, in gallery order. */
export const gofishIRExamples: readonly GofishIRExample[] = generatedExamples.map((e) => ({
  key: e.key,
  label: e.label,
  doc: e.doc as GofishDisplayListDocument,
  blurb: e.blurb,
  source: e.source,
}))
