import type { ChartSpec } from "./chartSpecCore"

export const REALTIME_CHART_SPECS: Record<string, ChartSpec> = {
  RealtimeLineChart: {
    name: "RealtimeLineChart",
    category: "realtime",
    description: "Streaming line chart rendered on canvas. Uses ref-based push API for high-frequency data.",
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    propBags: ["realtime"],
    ownProps: {
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      strokeDasharray: { type: "string" },
      transition: { type: "object", description: "Transition config: { duration, easing }" },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["live-stream"],
    },
  },

  RealtimeHistogram: {
    name: "RealtimeHistogram",
    category: "realtime",
    description: "Streaming bar chart with binned aggregation. Uses ref-based push API.",
    required: ["binSize"],
    dataShape: "realtime",
    dataAccessors: [],
    propBags: ["realtime"],
    ownProps: {
      binSize: { type: "number", description: "Time bin size in milliseconds (required)" },
      direction: { type: "string", enum: ["up", "down"] as const, default: "up", description: "Bar growth direction. Use \"down\" for mirrored histograms; explicit valueExtent is reversed." },
      categoryAccessor: { type: ["string", "function"], description: "Key for category grouping" },
      colors: { type: "object", description: "Map of category to color string" },
      fill: { type: "string" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      gap: { type: "number" },
      brush: { type: ["boolean", "string", "object"], description: "Enable brush selection. true defaults to { dimension: \"x\", snap: \"bin\" }. String: \"x\". Object: { dimension, snap: \"continuous\"|\"bin\", snapDuring }." },
      onBrush: { type: "function", description: "Callback when brush extent changes: (extent | null) => void" },
      linkedBrush: { type: ["string", "object"], description: "Cross-chart brush coordination via LinkedCharts. String: selection name. Object: { name, xField, yField }." },
      transition: { type: "object", description: "Transition config: { duration, easing }" },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["live-stream", "brush"],
    },
  },

  TemporalHistogram: {
    name: "TemporalHistogram",
    category: "realtime",
    description: "Static-data temporal histogram with binned aggregation. Use when data is a bounded array rather than a push stream.",
    required: ["data", "binSize"],
    dataShape: "array",
    dataAccessors: ["timeAccessor", "valueAccessor", "categoryAccessor"],
    propBags: [],
    ownProps: {
      data: { type: "array", description: "Array of temporal observations" },
      binSize: { type: "number", description: "Time bin size in milliseconds (required)" },
      size: { type: "array", description: "[width, height] in pixels" },
      width: { type: "number", description: "Alias for size[0]" },
      height: { type: "number", description: "Alias for size[1]" },
      margin: { type: "object", description: "Object margin. A side value of \"auto\" or null leaves that side available for auto-reservation." },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"], description: "Key for time/x values" },
      valueAccessor: { type: ["string", "function"], description: "Key for y values" },
      direction: { type: "string", enum: ["up", "down"] as const, default: "up", description: "Bar growth direction. Use \"down\" for mirrored histograms; explicit valueExtent is reversed." },
      categoryAccessor: { type: ["string", "function"], description: "Key for category grouping" },
      colors: { type: "object", description: "Map of category to color string" },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltip: { type: ["function", "object"], description: "Tooltip content function or config" },
      tooltipContent: { type: "function", omitFromSchema: true },
      onHover: { type: "function", omitFromSchema: true },
      annotations: { type: "array" },
      autoPlaceAnnotations: { type: ["boolean", "object"], description: "Opt-in annotation placement pass for note-like annotations without manual offsets." },
      responsiveRules: { type: "array", description: "Semantic responsive transforms applied before chart-mode defaults." },
      mobileSemantics: { type: "object", description: "Phone/mobile contract consumed by audits, recipes, adapters, and agents." },
      mobileInteraction: { type: ["boolean", "object"], description: "Touch-first interaction policy for phone-sized chart slots." },
      svgAnnotationRules: { type: "function", omitFromSchema: true },
      tickFormatTime: { type: "function", omitFromSchema: true },
      tickFormatValue: { type: "function", omitFromSchema: true },
      fill: { type: "string" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      gap: { type: "number" },
      linkedHover: { type: ["boolean", "string", "object"] },
      linkedBrush: { type: ["string", "object"], description: "Cross-chart brush coordination via LinkedCharts. String: selection name. Object: { name, xField, yField }." },
      brush: { type: ["boolean", "string", "object"], description: "Enable brush selection. true defaults to { dimension: \"x\", snap: \"bin\" }. String: \"x\". Object: { dimension, snap: \"continuous\"|\"bin\", snapDuring }." },
      onBrush: { type: "function", description: "Callback when brush extent changes: (extent | null) => void", omitFromSchema: true },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: false, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["brush"],
    },
  },

  RealtimeSwarmChart: {
    name: "RealtimeSwarmChart",
    category: "realtime",
    description: "Streaming swarm/scatter chart showing individual data points over time.",
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    propBags: ["realtime"],
    ownProps: {
      categoryAccessor: { type: ["string", "function"] },
      colors: { type: "object" },
      radius: { type: "number" },
      fill: { type: "string" },
      opacity: { type: "number" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      pointStyle: { type: "function", description: "Per-datum style callback. Overrides fill, stroke, strokeWidth, opacity, and radius via r.", omitFromSchema: true },
      yScaleType: { type: "string", enum: ["linear", "log", "symlog"], description: "Value-axis scale. symlog preserves zero and negative values while compressing large magnitudes." },
      transition: { type: "object", description: "Transition config: { duration, easing }" },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["live-stream"],
    },
  },

  RealtimeWaterfallChart: {
    name: "RealtimeWaterfallChart",
    category: "realtime",
    description: "Streaming waterfall chart with positive/negative bars and connectors.",
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    propBags: ["realtime"],
    ownProps: {
      positiveColor: { type: "string" },
      negativeColor: { type: "string" },
      connectorStroke: { type: "string" },
      connectorWidth: { type: "number" },
      gap: { type: "number" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      transition: { type: "object", description: "Transition config: { duration, easing }" },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["live-stream"],
    },
  },

  RealtimeHeatmap: {
    name: "RealtimeHeatmap",
    category: "realtime",
    description: "Streaming 2D heatmap with binned time and value aggregation.",
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    propBags: ["realtime"],
    ownProps: {
      heatmapXBins: { type: "number" },
      heatmapYBins: { type: "number" },
      aggregation: { type: "string", enum: ["count", "sum", "mean"] as const },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: false,
      colorModel: "sequential", layoutMode: "plugin",
      specialFeatures: ["live-stream"],
    },
  },

}
