import type { ChartSpec } from "./chartSpecCore"
import {
  ORIENTATION_ENUM
} from "./chartSpecCore"

export const NETWORK_CHART_SPECS: Record<string, ChartSpec> = {
  ForceDirectedGraph: {
    name: "ForceDirectedGraph",
    category: "network",
    description: "Physics-based node-link diagram. Use for relationships, social networks, knowledge graphs.",
    required: ["nodes", "edges"],
    dataShape: "network",
    dataAccessors: ["nodeIDAccessor", "sourceAccessor", "targetAccessor"],
    propBags: ["common"],
    ownProps: {
      styleRules: { type: "array", omitFromSchema: true, description: "Declarative threshold-aware styling: ordered { when, style } rules, last-applicable rule wins. A rule's fill may be a color or a HatchFill descriptor." },
      nodes: { type: "array", description: "Array of node objects" },
      edges: { type: "array", description: "Array of edge objects with source and target" },
      nodeIDAccessor: { type: ["string", "function"], default: "id", description: "Key for node unique identifier" },
      sourceAccessor: { type: ["string", "function"], default: "source", description: "Key for edge source node ID" },
      targetAccessor: { type: ["string", "function"], default: "target", description: "Key for edge target node ID" },
      nodeLabel: { type: ["string", "function"], description: "Key or accessor for node labels" },
      nodeSize: { type: ["number", "string", "function"], default: 8, description: "Fixed node radius or key for variable sizing" },
      nodeSizeRange: { type: "array", default: [5, 20] },
      edgeWidth: { type: ["number", "string", "function"], default: 1, description: "Fixed edge width or key for variable width" },
      edgeColor: { type: "string", default: "#999" },
      edgeOpacity: { type: "number", default: 0.6 },
      iterations: { type: "number", default: 300, description: "Force simulation iterations" },
      forceStrength: { type: "number", default: 0.1 },
      layoutExecution: { type: "string", enum: ["auto", "worker", "sync"] as const, default: "auto", description: "Force layout execution: auto, worker, or sync" },
      showLabels: { type: "boolean", default: false },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["force-simulation"],
    },
  },

  SankeyDiagram: {
    name: "SankeyDiagram",
    category: "network",
    description: "Flow diagram showing weighted connections between nodes. Use for flows, budgets, process mapping.",
    required: ["edges"],
    dataShape: "network",
    dataAccessors: ["sourceAccessor", "targetAccessor"],
    propBags: ["common"],
    ownProps: {
      styleRules: { type: "array", omitFromSchema: true, description: "Declarative threshold-aware styling: ordered { when, style } rules, last-applicable rule wins. A rule's fill may be a color or a HatchFill descriptor." },
      edges: { type: "array", description: "Array of edge objects with source, target, and value" },
      nodes: { type: "array", description: "Optional array of node objects (auto-derived from edges if omitted)" },
      sourceAccessor: { type: ["string", "function"], default: "source" },
      targetAccessor: { type: ["string", "function"], default: "target" },
      valueAccessor: { type: ["string", "function"], default: "value", description: "Key for edge flow value" },
      nodeIdAccessor: { type: ["string", "function"], default: "id" },
      edgeColorBy: { type: ["string", "function"], enum: ["source", "target", "gradient"] as const, default: "source", description: "How to color edges" },
      orientation: { type: "string", enum: ORIENTATION_ENUM, default: "horizontal" },
      nodeAlign: { type: "string", enum: ["justify", "left", "right", "center"] as const, default: "justify" },
      nodePaddingRatio: { type: "number", default: 0.05 },
      nodeWidth: { type: "number", default: 15 },
      nodeLabel: { type: ["string", "function"], description: "Key for node labels" },
      showLabels: { type: "boolean", default: true },
      edgeOpacity: { type: "number", default: 0.5 },
      // `edgeSort` is a comparator function — runtime-only.
      edgeSort: { type: "function", omitFromSchema: true },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: true, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: [],
    },
  },

  ProcessSankey: {
    name: "ProcessSankey",
    category: "network",
    description: "Temporal sankey with a real time x-axis. Edges carry startTime/endTime; nodes can declare an explicit xExtent lifetime. Use for timestamped flow events (PR commits, campaign-finance contributions, supply-chain shipments).",
    // `edges` is intentionally NOT required: ProcessSankey supports
    // push-mode where edges arrives via the ref. Only `domain` is
    // structurally required because the time axis can't degrade
    // without it.
    required: ["domain"],
    dataShape: "network",
    dataAccessors: ["sourceAccessor", "targetAccessor"],
    propBags: ["common"],
    ownProps: {
      edges: { type: "array", description: "Array of timed edge records with source, target, value, startTime, endTime. Omit for push-mode." },
      nodes: { type: "array", description: "Optional array of node objects. Nodes may carry an `xExtent: [start, end]` to bound the lane explicitly." },
      domain: { type: "array", description: "[tStart, tEnd] of the chart's x-axis (required)." },
      axisTicks: { type: "array", description: "Optional [{ date, label }] tick array for the time axis." },
      sourceAccessor: { type: ["string", "function"], default: "source" },
      targetAccessor: { type: ["string", "function"], default: "target" },
      valueAccessor: { type: ["string", "function"], default: "value" },
      nodeIdAccessor: { type: ["string", "function"], default: "id" },
      startTimeAccessor: { type: ["string", "function"], default: "startTime" },
      endTimeAccessor: { type: ["string", "function"], default: "endTime" },
      xExtentAccessor: { type: ["string", "function"], default: "xExtent" },
      edgeIdAccessor: { type: ["string", "function"], default: "id" },
      legendPosition: { type: "string", enum: ["right", "left", "top", "bottom"] as const, default: "right" },
      pairing: { type: "string", enum: ["value", "temporal"] as const, default: "temporal", description: "Edge-side pairing strategy at transit nodes." },
      packing: { type: "string", enum: ["off", "reuse"] as const, default: "reuse", description: "Lane reuse — pack lifetime-disjoint nodes into the same row." },
      laneOrder: { type: "string", enum: ["insertion", "crossing-min", "inside-out", "crossing-min+inside-out"] as const, default: "crossing-min" },
      ribbonLane: { type: "string", enum: ["source", "target", "both"] as const, default: "both" },
      lifetimeMode: { type: "string", enum: ["full", "half"] as const, default: "half" },
      showLaneRails: { type: "boolean", default: false },
      showQualityReadout: { type: "boolean", default: false },
      edgeOpacity: { type: "number", default: 0.35 },
      timeFormat: { type: "function", omitFromSchema: true },
      valueFormat: { type: "function", omitFromSchema: true },
      showParticles: { type: "boolean", default: false },
      particleStyle: { type: "object", description: "ParticleStyle config — same shape as SankeyDiagram. Defaults from DEFAULT_PARTICLE_STYLE (radius 3, opacity 0.7, spawnRate 0.1, maxPerEdge 50)." },
    },
    capabilities: {
      renderModes: ["hybrid"],
      // Selection/linkedHover are on BaseChartProps but the HOC hard-codes
      // them to undefined until wiring lands — do not claim support yet.
      supportsLegend: true, supportsSelection: false, supportsLinkedHover: false,
      supportsPush: true, supportsSSR: true,
      colorModel: "categorical", layoutMode: "custom",
      specialFeatures: ["temporal", "particles", "lane-reuse"],
    },
  },

  ChordDiagram: {
    name: "ChordDiagram",
    category: "network",
    description: "Circular diagram showing inter-relationships and flow volumes between groups.",
    required: ["edges"],
    dataShape: "network",
    dataAccessors: ["sourceAccessor", "targetAccessor"],
    propBags: ["common"],
    ownProps: {
      styleRules: { type: "array", omitFromSchema: true, description: "Declarative threshold-aware styling: ordered { when, style } rules, last-applicable rule wins. A rule's fill may be a color or a HatchFill descriptor." },
      edges: { type: "array", description: "Array of edge objects with source, target, and value" },
      nodes: { type: "array", description: "Optional array of node objects" },
      sourceAccessor: { type: ["string", "function"], default: "source" },
      targetAccessor: { type: ["string", "function"], default: "target" },
      valueAccessor: { type: ["string", "function"], default: "value" },
      nodeIdAccessor: { type: ["string", "function"], default: "id" },
      edgeColorBy: { type: ["string", "function"], enum: ["source", "target"] as const, default: "source" },
      padAngle: { type: "number", default: 0.01 },
      groupWidth: { type: "number", default: 20 },
      // `sortGroups` is a comparator function — runtime-only.
      sortGroups: { type: "function", omitFromSchema: true },
      nodeLabel: { type: ["string", "function"] },
      showLabels: { type: "boolean", default: true },
      edgeOpacity: { type: "number", default: 0.5 },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: false, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: true, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: [],
    },
  },

  TreeDiagram: {
    name: "TreeDiagram",
    category: "network",
    description: "Hierarchical tree layout. Supports tree, cluster, partition, and radial orientations. Data is a single root node with children.",
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    propBags: ["common"],
    ownProps: {
      data: { type: "object", description: "Root node object with nested children" },
      layout: { type: "string", enum: ["tree", "cluster", "partition", "treemap", "circlepack"] as const, default: "tree" },
      orientation: { type: "string", enum: ["vertical", "horizontal", "radial"] as const, default: "vertical" },
      childrenAccessor: { type: ["string", "function"], default: "children", description: "Key for the children array in each node" },
      valueAccessor: { type: ["string", "function"], default: "value" },
      nodeIdAccessor: { type: ["string", "function"], default: "name" },
      colorByDepth: { type: "boolean", default: false, description: "Color nodes by their depth in the hierarchy" },
      edgeStyle: { type: "string", enum: ["line", "curve"] as const, default: "curve" },
      nodeLabel: { type: ["string", "function"] },
      showLabels: { type: "boolean", default: true },
      nodeSize: { type: "number", default: 5 },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: false, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: false, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["hierarchy"],
    },
  },

  Treemap: {
    name: "Treemap",
    category: "network",
    description: "Space-filling rectangular hierarchy visualization. Data is a single root node with nested children.",
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    propBags: ["common"],
    ownProps: {
      data: { type: "object", description: "Root node object with nested children" },
      childrenAccessor: { type: ["string", "function"], default: "children" },
      valueAccessor: { type: ["string", "function"], default: "value" },
      nodeIdAccessor: { type: ["string", "function"], default: "name" },
      colorByDepth: { type: "boolean", default: false },
      showLabels: { type: "boolean", default: true },
      nodeLabel: { type: ["string", "function"] },
      nodeStyle: { type: "function", omitFromSchema: true, description: "Per-node style overlay merged on top of Treemap's built-in color encoding" },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: false, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: false, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["hierarchy"],
    },
  },

  CirclePack: {
    name: "CirclePack",
    category: "network",
    description: "Nested circles representing hierarchical data. Data is a single root node with nested children.",
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    propBags: ["common"],
    ownProps: {
      data: { type: "object", description: "Root node object with nested children" },
      childrenAccessor: { type: ["string", "function"], default: "children" },
      valueAccessor: { type: ["string", "function"], default: "value" },
      nodeIdAccessor: { type: ["string", "function"], default: "name" },
      colorByDepth: { type: "boolean", default: false },
      showLabels: { type: "boolean", default: true },
      nodeLabel: { type: ["string", "function"] },
      circleOpacity: { type: "number", default: 0.7 },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: false, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: false, supportsSSR: true,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["hierarchy"],
    },
  },

  OrbitDiagram: {
    name: "OrbitDiagram",
    category: "network",
    description: "Animated orbital diagram showing hierarchical data as nodes orbiting a center. Supports flat, solar, atomic, and custom ring arrangements.",
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    propBags: ["common"],
    ownProps: {
      data: { type: "object", description: "Hierarchical root object with children: { name: 'root', children: [...] }" },
      childrenAccessor: { type: ["string", "function"], default: "children", description: "Key to access children from each datum" },
      nodeIdAccessor: { type: ["string", "function"], default: "name", description: "Key to identify each node" },
      colorByDepth: { type: "boolean", default: false, description: "Color by hierarchy depth" },
      orbitMode: { type: ["string", "array"], default: "flat", description: "Ring arrangement: 'flat', 'solar', 'atomic', or number[]" },
      orbitSize: { type: ["number", "function"], default: 2.95, description: "Ring size divisor per depth" },
      speed: { type: "number", default: 0.25, description: "Orbit speed in degrees per frame" },
      eccentricity: { type: ["number", "function"], default: 1, description: "Vertical squash for elliptical orbits (1 = circle)" },
      showRings: { type: "boolean", default: true, description: "Show orbital ring paths" },
      nodeRadius: { type: ["number", "function"], default: 6, description: "Node radius" },
      showLabels: { type: "boolean", default: false, description: "Show node labels" },
      animated: { type: "boolean", default: true, description: "Enable animation" },
      // `revolution` is a per-node phase override — runtime-only.
      revolution: { type: "function", omitFromSchema: true },
      // `foregroundGraphics` is a render-on-top escape hatch (StreamFrame
      // pass-through), runtime-only.
      foregroundGraphics: { type: "object", omitFromSchema: true },
    },
    capabilities: {
      renderModes: ["hybrid"],
      supportsLegend: false, supportsSelection: true, supportsLinkedHover: true,
      supportsPush: false, supportsSSR: false,
      colorModel: "categorical", layoutMode: "plugin",
      specialFeatures: ["hierarchy", "animated", "hoc-ssr-only"],
    },
  },

  // ─── Geo family ──────────────────────────────────────────────────────

}
