/**
 * Pure helpers for the three spreads that recur in every XY / ordinal /
 * geo HOC's `streamProps = { ... }` object literal:
 *
 *   1. Base metadata — `title`, `description`, `summary`, `accessibleTable`,
 *      `className`, `animate`. Each gets a per-field condition (truthy
 *      vs. defined) so the frame doesn't receive empty strings or
 *      `undefined` values that override its own defaults.
 *
 *   2. Custom hover/click behavior — conditionally include
 *      `customHoverBehavior` / `customClickBehavior` from `useChartSetup`
 *      output, gated on whether any consumer-side handler asked for them
 *      (`linkedHover`, `onObservation`, `onClick`, `hoverHighlight`).
 *
 *   3. Tooltip — `tooltip === false ? () => null : normalizeTooltip(tooltip) || default`.
 *
 * These are extractions, not abstractions. The bodies were already
 * identical across ~25 HOC sites; centralizing them eliminates ~240
 * lines of mechanical boilerplate without changing a single runtime
 * behavior. Network HOCs use a different (JSX-prop) construction
 * pattern and are intentionally NOT in scope.
 */
"use client"
import type { ReactNode } from "react"
import type { Datum } from "./datumTypes"
import { normalizeTooltip, type TooltipProp } from "../../Tooltip/Tooltip"
import type { HoverData } from "../../realtime/types"
import type { LinkedHoverProp, SelectionConfig } from "./types"
import type { OnObservationCallback } from "../../store/ObservationStore"
import type { AnimateProp } from "../../stream/pipelineTransitionUtils"

/**
 * The frames accept `tooltipContent: (d: HoverData) => ReactNode`,
 * which is a slightly wider parameter than the `TooltipContentFn`
 * (`(d: Datum) => ReactNode`) the `Tooltip` module exports. The HOC
 * default tooltip generated by `buildDefaultTooltip` matches the
 * wider shape; user-provided tooltip functions (via `normalizeTooltip`)
 * conform to the narrower `Datum` shape. At runtime both work because
 * `HoverData` carries the original `Datum` plus interaction metadata,
 * and the user's tooltip body reads only fields it knows about.
 *
 * Typing the helper's return at the wider `HoverData` shape lets either
 * source flow through without a cast at the call site, matching the
 * inline form HOCs used before this refactor.
 */
type FrameTooltipContent = (d: HoverData) => ReactNode

/**
 * Returns the spreadable subset of base metadata props for the frame.
 *
 *   - Truthy gate for `title` / `description` / `summary` / `className`:
 *     empty strings should NOT shadow the frame's own defaults.
 *   - Defined gate for `accessibleTable`: an explicit `false` is a real
 *     consumer choice (suppresses the sr-only data table) and must
 *     reach the frame.
 *   - Defined-and-non-null gate for `animate`: matches `props.animate
 *     != null`. Lets `false` through (disables animation explicitly)
 *     while filtering `undefined` so the frame's intro-on-default
 *     stays in effect.
 *
 * The returned object is suitable for `...spread` into a frame-props
 * object literal.
 */
export interface BaseMetadataProps {
  title?: string | ReactNode
  description?: string
  summary?: string
  accessibleTable?: boolean
  className?: string
  animate?: AnimateProp
}

export function buildBaseMetadataProps(input: BaseMetadataProps): BaseMetadataProps {
  const { title, description, summary, accessibleTable, className, animate } = input
  // Returning `BaseMetadataProps` rather than `Record<string, unknown>`
  // preserves per-key types on the spread site, so a typo like
  // `{ titel }` in this helper body would fail the return contract
  // and a consumer mis-spreading the result into a frame prop would
  // get the same field-by-field check it had before the extraction.
  const out: BaseMetadataProps = {}
  if (title) out.title = title
  if (description) out.description = description
  if (summary) out.summary = summary
  if (accessibleTable !== undefined) out.accessibleTable = accessibleTable
  if (className) out.className = className
  if (animate != null) out.animate = animate
  return out
}

/**
 * Returns the spreadable hover/click behavior props for the frame.
 *
 * The predicates encode the same logic the HOCs already used inline:
 *
 *   - `customHoverBehavior` is forwarded only when at least one
 *     consumer-side hover-driving prop is set (`linkedHover` for
 *     cross-chart highlight, `onObservation` for AI observation
 *     emission, `onClick` for click resolution that needs hover-driven
 *     hit testing, `hoverHighlight` for the dim-non-hovered effect).
 *   - `customClickBehavior` mirrors the click-driving subset
 *     (`onObservation`, `onClick`, `linkedHover` for cross-chart
 *     selection lock).
 *
 * Returning the props as a spreadable object means HOCs that don't
 * need either get an empty merge that adds nothing.
 */
export function buildCustomBehaviorProps(input: {
  linkedHover?: LinkedHoverProp
  onObservation?: OnObservationCallback
  onClick?: ((datum: Datum, position: { x: number; y: number }) => void) | undefined
  hoverHighlight?: boolean
  customHoverBehavior: (d: Datum | null) => void
  customClickBehavior: (d: Datum | null) => void
  /**
   * Whether `linkedHover` participates in the click predicate. Most
   * XY / ordinal HOCs say yes — `linkedHover` cross-chart selection
   * fires on click-to-lock as well as hover. Geo HOCs and
   * `CandlestickChart` say no — their click resolution only needs
   * direct consumer-side handlers (`onObservation` / `onClick`).
   * Default is `true` to match the more common case.
   */
  linkedHoverInClickPredicate?: boolean
}): {
  customHoverBehavior?: (d: Datum | null) => void
  customClickBehavior?: (d: Datum | null) => void
} {
  const {
    linkedHover,
    onObservation,
    onClick,
    hoverHighlight,
    customHoverBehavior,
    customClickBehavior,
    linkedHoverInClickPredicate = true,
  } = input
  const out: {
    customHoverBehavior?: (d: Datum | null) => void
    customClickBehavior?: (d: Datum | null) => void
  } = {}
  if (linkedHover || onObservation || onClick || hoverHighlight) {
    out.customHoverBehavior = customHoverBehavior
  }
  const clickPredicate = linkedHoverInClickPredicate
    ? (onObservation || onClick || linkedHover)
    : (onObservation || onClick)
  if (clickPredicate) {
    out.customClickBehavior = customClickBehavior
  }
  return out
}

/**
 * Resolve the `tooltipContent` prop for the frame.
 *
 *   - `tooltip === false` → noop function (suppresses the frame's
 *     default tooltip rendering entirely).
 *   - Otherwise → `normalizeTooltip(tooltip)` (a function, possibly
 *     returned by `Tooltip({ ... })` / `MultiLineTooltip({ ... })`),
 *     falling back to the chart's own `defaultTooltipContent` if
 *     `tooltip` is undefined or an unrecognized form.
 *
 * Returning `tooltipContent` as an object means HOCs spread it like
 * the other helpers and don't have to remember the noop-vs-default
 * branch in line.
 */
export function buildTooltipProps(input: {
  tooltip: TooltipProp | undefined
  defaultTooltipContent: FrameTooltipContent
}): { tooltipContent: FrameTooltipContent } {
  const { tooltip, defaultTooltipContent } = input
  // Cast at the boundary: `normalizeTooltip` returns the narrower
  // Datum-parameter shape, the frame slot wants the wider HoverData
  // shape. Both work at runtime because HoverData carries the Datum;
  // the cast preserves the inline HOC form's semantics.
  const tooltipContent: FrameTooltipContent =
    tooltip === false
      ? () => null
      : (normalizeTooltip(tooltip) as FrameTooltipContent | false) || defaultTooltipContent
  return { tooltipContent }
}

/**
 * Selection-config alias. Re-exported so HOCs that use these helpers
 * don't need a parallel import path for the type that flows through
 * `buildCustomBehaviorProps`.
 */
export type { SelectionConfig }
