/**
 * Per-component prop specifications for validation.
 *
 * Pure data — one ComponentSpec entry per Semiotic HOC chart.
 * Shared prop fragments (commonProps, xyAxisProps, etc.) are composed
 * via spread to keep individual entries concise.
 *
 * Consumed by: validateProps.ts (validation engine), diagnoseConfig.ts,
 *              chartConfig.ts, check-schema-freshness.js
 */
import type { PropDef, ComponentSpec } from "./validateProps"

// ---------------------------------------------------------------------------
// Shared prop definitions (reused across many components)
// ---------------------------------------------------------------------------

const commonProps: Record<string, PropDef> = {
  width: { type: "number" },
  height: { type: "number" },
  margin: { type: "object" },
  className: { type: "string" },
  title: { type: "string" },
  enableHover: { type: "boolean" },
  showLegend: { type: "boolean" },
  showGrid: { type: "boolean" },
  colorBy: { type: ["string", "function"] },
  colorScheme: { type: ["string", "array"] },
  tooltip: { type: ["boolean", "function", "object"] },
  annotations: { type: "array" },
  frameProps: { type: "object" },
  onClick: { type: "function" },
}

const xyAxisProps: Record<string, PropDef> = {
  xLabel: { type: "string" },
  yLabel: { type: "string" },
  xFormat: { type: "function" },
  yFormat: { type: "function" },
}

const ordinalAxisProps: Record<string, PropDef> = {
  categoryLabel: { type: "string" },
  valueLabel: { type: "string" },
  valueFormat: { type: "function" },
  categoryFormat: { type: "function" },
}

const curveEnum = [
  "linear", "monotoneX", "monotoneY", "step",
  "stepAfter", "stepBefore", "basis", "cardinal", "catmullRom",
] as const

const orientationEnum = ["vertical", "horizontal"] as const

// ---------------------------------------------------------------------------
// Validation map — one entry per component
// ---------------------------------------------------------------------------

export const VALIDATION_MAP: Record<string, ComponentSpec> = {
  // -- XY Charts --
  LineChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      lineBy: { type: ["string", "function"] },
      lineDataAccessor: { type: "string" },
      curve: { type: "string", enum: curveEnum as unknown as string[] },
      lineWidth: { type: "number" },
      showPoints: { type: "boolean" },
      pointRadius: { type: "number" },
      fillArea: { type: "boolean" },
      areaOpacity: { type: "number" },
    },
  },

  AreaChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      areaBy: { type: ["string", "function"] },
      lineDataAccessor: { type: "string" },
      curve: { type: "string", enum: curveEnum as unknown as string[] },
      areaOpacity: { type: "number" },
      showLine: { type: "boolean" },
      lineWidth: { type: "number" },
    },
  },

  StackedAreaChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      areaBy: { type: ["string", "function"] },
      lineDataAccessor: { type: "string" },
      curve: { type: "string", enum: curveEnum as unknown as string[] },
      areaOpacity: { type: "number" },
      showLine: { type: "boolean" },
      lineWidth: { type: "number" },
      normalize: { type: "boolean" },
    },
  },

  Scatterplot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      sizeBy: { type: ["string", "function"] },
      sizeRange: { type: "array" },
      pointRadius: { type: "number" },
      pointOpacity: { type: "number" },
    },
  },

  BubbleChart: {
    required: ["data", "sizeBy"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      sizeBy: { type: ["string", "function"] },
      sizeRange: { type: "array" },
      bubbleOpacity: { type: "number" },
      bubbleStrokeWidth: { type: "number" },
      bubbleStrokeColor: { type: "string" },
    },
  },

  Heatmap: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      colorScheme: { type: "string", enum: ["blues", "reds", "greens", "viridis", "custom"] },
      customColorScale: { type: ["object", "function"] },
      showValues: { type: "boolean" },
      valueFormat: { type: "function" },
      cellBorderColor: { type: "string" },
      cellBorderWidth: { type: "number" },
      showLegend: { type: "boolean" },
      legendPosition: { type: "string", enum: ["right", "left", "top", "bottom"] },
    },
  },

  QuadrantChart: {
    required: ["quadrants"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      quadrants: { type: "object" },
      xCenter: { type: "number" },
      yCenter: { type: "number" },
      centerlineStyle: { type: "object" },
      showQuadrantLabels: { type: "boolean" },
      quadrantLabelSize: { type: "number" },
      sizeBy: { type: ["string", "function"] },
      sizeRange: { type: "array" },
      pointRadius: { type: "number" },
      pointOpacity: { type: "number" },
    },
  },

  MultiAxisLineChart: {
    required: ["series"],
    dataShape: "array",
    dataAccessors: ["xAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      series: { type: "array" },
      colorScheme: { type: ["string", "array"] },
      curve: { type: "string" },
      lineWidth: { type: "number" },
      annotations: { type: "array" },
    },
  },

  ConnectedScatterplot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["xAccessor", "yAccessor"],
    props: {
      ...commonProps,
      ...xyAxisProps,
      data: { type: "array" },
      xAccessor: { type: ["string", "function"] },
      yAccessor: { type: ["string", "function"] },
      orderAccessor: { type: ["string", "function"] },
      orderLabel: { type: "string" },
      pointRadius: { type: "number" },
      pointIdAccessor: { type: ["string", "function"] },
      annotations: { type: "array" },
    },
  },

  // -- Ordinal Charts --
  BarChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      sort: { type: ["boolean", "string", "function"] },
      barPadding: { type: "number" },
    },
  },

  StackedBarChart: {
    required: ["data", "stackBy"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      stackBy: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      normalize: { type: "boolean" },
      barPadding: { type: "number" },
    },
  },

  LikertChart: {
    required: ["levels"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor", "levelAccessor", "countAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      levelAccessor: { type: ["string", "function"] },
      countAccessor: { type: ["string", "function"] },
      levels: { type: "array" },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      barPadding: { type: "number" },
    },
  },

  GroupedBarChart: {
    required: ["data", "groupBy"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      groupBy: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      barPadding: { type: "number" },
    },
  },

  SwarmPlot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      sizeBy: { type: ["string", "function"] },
      sizeRange: { type: "array" },
      pointRadius: { type: "number" },
      pointOpacity: { type: "number" },
      categoryPadding: { type: "number" },
      brush: { type: "boolean" },
      onBrush: { type: "function" },
      linkedBrush: { type: ["string", "object"] },
    },
  },

  BoxPlot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      showOutliers: { type: "boolean" },
      outlierRadius: { type: "number" },
      categoryPadding: { type: "number" },
    },
  },

  Histogram: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      bins: { type: "number" },
      relative: { type: "boolean" },
      categoryPadding: { type: "number" },
      brush: { type: "boolean" },
      onBrush: { type: "function" },
      linkedBrush: { type: ["string", "object"] },
    },
  },

  ViolinPlot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      bins: { type: "number" },
      curve: { type: "string" },
      showIQR: { type: "boolean" },
      categoryPadding: { type: "number" },
      brush: { type: "boolean" },
      onBrush: { type: "function" },
      linkedBrush: { type: ["string", "object"] },
    },
  },

  RidgelinePlot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      bins: { type: "number" },
      amplitude: { type: "number" },
      categoryPadding: { type: "number" },
    },
  },

  DotPlot: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      sort: { type: ["boolean", "string", "function"] },
      dotRadius: { type: "number" },
      categoryPadding: { type: "number" },
    },
  },

  PieChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      startAngle: { type: "number" },
    },
  },

  DonutChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      innerRadius: { type: "number" },
      centerContent: { type: ["object", "string", "number"] },
      startAngle: { type: "number" },
    },
  },

  FunnelChart: {
    required: ["data"],
    dataShape: "array",
    dataAccessors: ["stepAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      stepAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      categoryAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: ["horizontal", "vertical"] as unknown as string[] },
      connectorOpacity: { type: "number" },
      showCategoryTicks: { type: "boolean" },
      responsiveWidth: { type: "boolean" },
      legendPosition: { type: "string", enum: ["right", "left", "top", "bottom"] as unknown as string[] },
    },
  },

  SwimlaneChart: {
    required: ["subcategoryAccessor"],
    dataShape: "array",
    dataAccessors: ["categoryAccessor", "subcategoryAccessor", "valueAccessor"],
    props: {
      ...commonProps,
      ...ordinalAxisProps,
      data: { type: "array" },
      categoryAccessor: { type: ["string", "function"] },
      subcategoryAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      orientation: { type: "string", enum: ["horizontal", "vertical"] as unknown as string[] },
      barPadding: { type: "number" },
      showCategoryTicks: { type: "boolean" },
      brush: { type: "boolean" },
      onBrush: { type: "function" },
      linkedBrush: { type: ["string", "object"] },
      responsiveWidth: { type: "boolean" },
      legendPosition: { type: "string", enum: ["right", "left", "top", "bottom"] as unknown as string[] },
    },
  },

  // -- Network Charts --
  ForceDirectedGraph: {
    required: ["nodes", "edges"],
    dataShape: "network",
    dataAccessors: ["nodeIDAccessor", "sourceAccessor", "targetAccessor"],
    props: {
      ...commonProps,
      nodes: { type: "array" },
      edges: { type: "array" },
      nodeIDAccessor: { type: ["string", "function"] },
      sourceAccessor: { type: ["string", "function"] },
      targetAccessor: { type: ["string", "function"] },
      nodeLabel: { type: ["string", "function"] },
      nodeSize: { type: ["number", "string", "function"] },
      nodeSizeRange: { type: "array" },
      edgeWidth: { type: ["number", "string", "function"] },
      edgeColor: { type: "string" },
      edgeOpacity: { type: "number" },
      iterations: { type: "number" },
      forceStrength: { type: "number" },
      showLabels: { type: "boolean" },
    },
  },

  SankeyDiagram: {
    required: ["edges"],
    dataShape: "network",
    dataAccessors: ["sourceAccessor", "targetAccessor"],
    props: {
      ...commonProps,
      nodes: { type: "array" },
      edges: { type: "array" },
      sourceAccessor: { type: ["string", "function"] },
      targetAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      edgeColorBy: { type: ["string", "function"], enum: ["source", "target", "gradient"] },
      orientation: { type: "string", enum: orientationEnum as unknown as string[] },
      nodeAlign: { type: "string", enum: ["justify", "left", "right", "center"] },
      nodePaddingRatio: { type: "number" },
      nodeWidth: { type: "number" },
      nodeLabel: { type: ["string", "function"] },
      showLabels: { type: "boolean" },
      edgeOpacity: { type: "number" },
      edgeSort: { type: "function" },
    },
  },

  ChordDiagram: {
    required: ["edges"],
    dataShape: "network",
    dataAccessors: ["sourceAccessor", "targetAccessor"],
    props: {
      ...commonProps,
      nodes: { type: "array" },
      edges: { type: "array" },
      sourceAccessor: { type: ["string", "function"] },
      targetAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      edgeColorBy: { type: ["string", "function"], enum: ["source", "target"] },
      padAngle: { type: "number" },
      groupWidth: { type: "number" },
      sortGroups: { type: "function" },
      nodeLabel: { type: ["string", "function"] },
      showLabels: { type: "boolean" },
      edgeOpacity: { type: "number" },
    },
  },

  TreeDiagram: {
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    props: {
      ...commonProps,
      data: { type: "object" },
      layout: { type: "string", enum: ["tree", "cluster", "partition", "treemap", "circlepack"] },
      orientation: { type: "string", enum: ["vertical", "horizontal", "radial"] },
      childrenAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      colorByDepth: { type: "boolean" },
      edgeStyle: { type: "string", enum: ["line", "curve"] },
      nodeLabel: { type: ["string", "function"] },
      showLabels: { type: "boolean" },
      nodeSize: { type: "number" },
    },
  },

  Treemap: {
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    props: {
      ...commonProps,
      data: { type: "object" },
      childrenAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      colorByDepth: { type: "boolean" },
      showLabels: { type: "boolean" },
      nodeLabel: { type: ["string", "function"] },
    },
  },

  CirclePack: {
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    props: {
      ...commonProps,
      data: { type: "object" },
      childrenAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      colorByDepth: { type: "boolean" },
      showLabels: { type: "boolean" },
      nodeLabel: { type: ["string", "function"] },
      circleOpacity: { type: "number" },
    },
  },

  OrbitDiagram: {
    required: ["data"],
    dataShape: "object",
    dataAccessors: [],
    props: {
      ...commonProps,
      data: { type: "object" },
      childrenAccessor: { type: ["string", "function"] },
      nodeIdAccessor: { type: ["string", "function"] },
      orbitMode: { type: ["string", "array"] },
      speed: { type: "number" },
      revolution: { type: "function" },
      eccentricity: { type: ["number", "function"] },
      orbitSize: { type: ["number", "function"] },
      nodeRadius: { type: ["number", "function"] },
      showRings: { type: "boolean" },
      showLabels: { type: "boolean" },
      animated: { type: "boolean" },
      colorByDepth: { type: "boolean" },
      annotations: { type: "array" },
      foregroundGraphics: { type: "object" },
    },
  },

  // -- Realtime Charts --
  RealtimeLineChart: {
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    props: {
      size: { type: "array" },
      margin: { type: "object" },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      windowSize: { type: "number" },
      windowMode: { type: "string", enum: ["sliding", "stepping"] },
      arrowOfTime: { type: "string", enum: ["left", "right"] },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      strokeDasharray: { type: "string" },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltipContent: { type: "function" },
      tooltip: { type: ["function", "object"] },
      onHover: { type: "function" },
      annotations: { type: "array" },
      svgAnnotationRules: { type: "function" },
      tickFormatTime: { type: "function" },
      tickFormatValue: { type: "function" },
      width: { type: "number" },
      height: { type: "number" },
      decay: { type: "object" },
      pulse: { type: "object" },
      staleness: { type: "object" },
      transition: { type: "object" },
    },
  },

  RealtimeHistogram: {
    required: ["binSize"],
    dataShape: "realtime",
    dataAccessors: [],
    props: {
      binSize: { type: "number" },
      size: { type: "array" },
      margin: { type: "object" },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      categoryAccessor: { type: ["string", "function"] },
      colors: { type: "object" },
      windowSize: { type: "number" },
      windowMode: { type: "string", enum: ["sliding", "stepping"] },
      arrowOfTime: { type: "string", enum: ["left", "right"] },
      fill: { type: "string" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      gap: { type: "number" },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltipContent: { type: "function" },
      tooltip: { type: ["function", "object"] },
      onHover: { type: "function" },
      annotations: { type: "array" },
      svgAnnotationRules: { type: "function" },
      tickFormatTime: { type: "function" },
      tickFormatValue: { type: "function" },
      width: { type: "number" },
      height: { type: "number" },
      decay: { type: "object" },
      pulse: { type: "object" },
      staleness: { type: "object" },
      transition: { type: "object" },
    },
  },

  RealtimeSwarmChart: {
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    props: {
      size: { type: "array" },
      margin: { type: "object" },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      categoryAccessor: { type: ["string", "function"] },
      colors: { type: "object" },
      windowSize: { type: "number" },
      windowMode: { type: "string", enum: ["sliding", "stepping"] },
      arrowOfTime: { type: "string", enum: ["left", "right"] },
      radius: { type: "number" },
      fill: { type: "string" },
      opacity: { type: "number" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltipContent: { type: "function" },
      tooltip: { type: ["function", "object"] },
      onHover: { type: "function" },
      annotations: { type: "array" },
      svgAnnotationRules: { type: "function" },
      tickFormatTime: { type: "function" },
      tickFormatValue: { type: "function" },
      width: { type: "number" },
      height: { type: "number" },
      decay: { type: "object" },
      pulse: { type: "object" },
      staleness: { type: "object" },
      transition: { type: "object" },
    },
  },

  RealtimeWaterfallChart: {
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    props: {
      size: { type: "array" },
      margin: { type: "object" },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      windowSize: { type: "number" },
      windowMode: { type: "string", enum: ["sliding", "stepping"] },
      arrowOfTime: { type: "string", enum: ["left", "right"] },
      positiveColor: { type: "string" },
      negativeColor: { type: "string" },
      connectorStroke: { type: "string" },
      connectorWidth: { type: "number" },
      gap: { type: "number" },
      stroke: { type: "string" },
      strokeWidth: { type: "number" },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltipContent: { type: "function" },
      tooltip: { type: ["function", "object"] },
      onHover: { type: "function" },
      annotations: { type: "array" },
      svgAnnotationRules: { type: "function" },
      tickFormatTime: { type: "function" },
      tickFormatValue: { type: "function" },
      width: { type: "number" },
      height: { type: "number" },
      decay: { type: "object" },
      pulse: { type: "object" },
      staleness: { type: "object" },
      transition: { type: "object" },
    },
  },

  RealtimeHeatmap: {
    required: [],
    dataShape: "realtime",
    dataAccessors: [],
    props: {
      size: { type: "array" },
      margin: { type: "object" },
      className: { type: "string" },
      timeAccessor: { type: ["string", "function"] },
      valueAccessor: { type: ["string", "function"] },
      heatmapXBins: { type: "number" },
      heatmapYBins: { type: "number" },
      aggregation: { type: "string", enum: ["count", "sum", "mean"] },
      windowSize: { type: "number" },
      windowMode: { type: "string", enum: ["sliding", "stepping"] },
      arrowOfTime: { type: "string", enum: ["left", "right"] },
      timeExtent: { type: "array" },
      valueExtent: { type: "array" },
      extentPadding: { type: "number" },
      showAxes: { type: "boolean" },
      background: { type: "string" },
      enableHover: { type: ["boolean", "object"] },
      tooltipContent: { type: "function" },
      tooltip: { type: ["function", "object"] },
      onHover: { type: "function" },
      annotations: { type: "array" },
      svgAnnotationRules: { type: "function" },
      tickFormatTime: { type: "function" },
      tickFormatValue: { type: "function" },
      width: { type: "number" },
      height: { type: "number" },
      decay: { type: "object" },
      pulse: { type: "object" },
      staleness: { type: "object" },
    },
  },
}
