language: node_js

node_js:
  - "lts/*"
  - "8"

install:
  - npm install

script:
  # - npm run lint  # disabled in current semiotic
  - npm run test --coverage

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

cache:
  directories:
    - "node_modules"
