import React, { useMemo, useState } from "react"
import { PhysicsPileChart } from "semiotic/physics"

import ComponentMeta from "../../components/ComponentMeta"
import PropTable from "../../components/PropTable"
import PageLayout from "../../components/PageLayout"
import ChartGrounding from "../../components/ChartGrounding"

const pileData = [
  { id: "orders", category: "Orders", value: 18 },
  { id: "queued", category: "Queued", value: 11 },
  { id: "review", category: "Review", value: 7 },
  { id: "done", category: "Done", value: 24 },
]

const mechanicalCategoryOptions = ["Intake", "Triage", "Review", "Build", "Verify", "Ship"]

const physicsPileChartProps = [
  { name: "data", type: "array", required: false, default: null, description: "Rows to unitize into category piles. Optional when mode is mechanical." },
  { name: "categoryAccessor", type: "string | function", required: false, default: '"category"', description: "Categorical field that chooses the pile." },
  { name: "valueAccessor", type: "string | function", required: false, default: '"value"', description: "Numeric field converted into unit bodies." },
  { name: "mode", type: '"sample" | "mechanical"', required: false, default: '"sample"', description: "Use data values or generate a deterministic no-data unit pile." },
  { name: "mechanicalCount", type: "number", required: false, default: "max(48, categories * 12)", description: "Number of generated unit bodies in mechanical mode." },
  { name: "mechanicalCategories", type: "array", required: false, default: '["Intake", "Review", "Build", "Ship"]', description: "Category labels generated by mechanical mode." },
  { name: "unitValue", type: "number", required: false, default: "1", description: "Value represented by one body." },
  { name: "ballRadius", type: "number", required: false, default: "5", description: "Radius for each simulated unit body." },
  { name: "colorBy", type: "string | function", required: false, default: null, description: "Categorical field used to color bodies." },
  { name: "seed", type: "number", required: false, default: "1", description: "Deterministic simulation seed." },
  { name: "showProjection", type: "boolean", required: false, default: "true", description: "Draw an exact settled-projection overlay so totals remain readable while units settle." },
  { name: "sediment", type: "boolean", required: false, default: null, description: "Reserved future sediment mode." },
  { name: "size", type: "array", required: false, default: "[700, 380]", description: "[width, height] in pixels." },
  { name: "width", type: "number", required: false, default: "700", description: "Width alias used when size is omitted." },
  { name: "height", type: "number", required: false, default: "380", description: "Height alias used when size is omitted." },
  { name: "hoverRadius", type: "number", required: false, default: "16", description: "Pixel hit radius for unit-body hover tooltips." },
  { name: "paused", type: "boolean", required: false, default: "false", description: "Pause the simulation." },
  { name: "tooltip", type: "boolean | function | object", required: false, default: "true", description: "Enable the default unit-body tooltip, pass a custom tooltip renderer/config, or set false to disable hover tooltips." },
  { name: "frameProps", type: "object", required: false, default: null, description: "Advanced StreamPhysicsFrame props." },
]

const controlPanelStyle = {
  display: "flex",
  flexWrap: "wrap",
  gap: 12,
  alignItems: "end",
  margin: "0 0 12px",
  padding: 12,
  border: "1px solid var(--surface-3)",
  borderRadius: 8,
  background: "var(--surface-1)",
}

const controlLabelStyle = {
  display: "grid",
  gap: 6,
  color: "var(--text-secondary)",
  fontSize: 12,
  fontWeight: 800,
  textTransform: "uppercase",
}

const segmentStyle = {
  display: "inline-flex",
  overflow: "hidden",
  border: "1px solid var(--surface-3)",
  borderRadius: 7,
}

const buttonStyle = {
  minHeight: 34,
  padding: "0 12px",
  border: 0,
  borderRight: "1px solid var(--surface-3)",
  background: "var(--surface-0)",
  color: "var(--text-primary)",
  fontWeight: 800,
  cursor: "pointer",
}

const activeButtonStyle = {
  ...buttonStyle,
  background: "#244f72",
  color: "#fff",
}

const inputStyle = {
  minHeight: 34,
  minWidth: 160,
  border: "1px solid var(--surface-3)",
  borderRadius: 6,
  background: "var(--surface-0)",
  color: "var(--text-primary)",
  padding: "0 8px",
}

export default function PhysicsPileChartPage() {
  const [mode, setMode] = useState("sample")
  const [mechanicalCount, setMechanicalCount] = useState(80)
  const [mechanicalCategoryCount, setMechanicalCategoryCount] = useState(4)
  const mechanicalCategories = useMemo(
    () => mechanicalCategoryOptions.slice(0, mechanicalCategoryCount),
    [mechanicalCategoryCount],
  )
  const demoProps = useMemo(
    () =>
      mode === "mechanical"
        ? {
            mode,
            mechanicalCount,
            mechanicalCategories,
            colorBy: "category",
            title: "Mechanical capacity sketch",
          }
        : {
            data: pileData,
            categoryAccessor: "category",
            valueAccessor: "value",
            colorBy: "category",
            title: "Work queue units",
          },
    [mechanicalCategories, mechanicalCount, mode],
  )
  const chartKey = `${mode}-${mechanicalCount}-${mechanicalCategoryCount}`

  return (
    <PageLayout
      title="PhysicsPileChart"
      tier="charts"
      breadcrumbs={[
        { label: "Charts", path: "/charts" },
        { label: "Physics", path: "/charts/physics-pile-chart" },
        { label: "PhysicsPileChart", path: "/charts/physics-pile-chart" },
      ]}
      prevPage={{ title: "EventDropChart", path: "/charts/event-drop-chart" }}
      nextPage={{ title: "CollisionSwarmChart", path: "/charts/collision-swarm-chart" }}
    >
      <ComponentMeta
        componentName="PhysicsPileChart"
        importStatement='import { PhysicsPileChart } from "semiotic/physics"'
        tier="charts"
        wraps="StreamPhysicsFrame"
        wrapsPath="/dev/physics-frame"
        related={[
          { name: "GaltonBoardChart", path: "/charts/galton-board-chart" },
          { name: "EventDropChart", path: "/charts/event-drop-chart" },
          { name: "CollisionSwarmChart", path: "/charts/collision-swarm-chart" },
          { name: "PhysicsCustomChart", path: "/charts/physics-custom-chart" },
          { name: "BarChart", path: "/charts/bar-chart" },
        ]}
      />

      <ChartGrounding
        component="PhysicsPileChart"
        props={{
          data: pileData,
          categoryAccessor: "category",
          valueAccessor: "value",
          unitValue: 1,
          title: "Work queue units",
        }}
      />

      <h2 id="example">Example</h2>
      <div style={controlPanelStyle} aria-label="Physics pile controls">
        <div style={controlLabelStyle}>
          <span>Mode</span>
          <div style={segmentStyle}>
            <button
              type="button"
              style={mode === "sample" ? activeButtonStyle : buttonStyle}
              onClick={() => setMode("sample")}
            >
              Sample
            </button>
            <button
              type="button"
              style={{
                ...(mode === "mechanical" ? activeButtonStyle : buttonStyle),
                borderRight: 0,
              }}
              onClick={() => setMode("mechanical")}
            >
              Mechanical
            </button>
          </div>
        </div>
        {mode === "mechanical" && (
          <>
            <label style={controlLabelStyle}>
              Generated units
              <select
                style={inputStyle}
                value={mechanicalCount}
                onChange={(event) => setMechanicalCount(Number(event.target.value))}
              >
                <option value={48}>48</option>
                <option value={80}>80</option>
                <option value={128}>128</option>
              </select>
            </label>
            <label style={controlLabelStyle}>
              Categories
              <select
                style={inputStyle}
                value={mechanicalCategoryCount}
                onChange={(event) => setMechanicalCategoryCount(Number(event.target.value))}
              >
                <option value={3}>3</option>
                <option value={4}>4</option>
                <option value={6}>6</option>
              </select>
            </label>
          </>
        )}
      </div>
      <div style={{ overflowX: "auto", border: "1px solid var(--surface-3)", borderRadius: 8, padding: 12 }}>
        <PhysicsPileChart
          key={chartKey}
          {...demoProps}
          unitValue={1}
          size={[640, 320]}
        />
      </div>
      <p>
        Mechanical mode generates seeded category totals without requiring input data. Use it for
        capacity sketches, design reviews, or empty-state demos; switch back to sample mode when
        real rows should determine each pile.
      </p>
      <p>
        The faint projection overlay is the truth layer: it preserves exact category totals while
        the physics layer shows the units settling. Set <code>showProjection=&#123;false&#125;</code>{" "}
        when you need an unadorned simulation.
      </p>

      <h2 id="props">Props</h2>
      <PropTable componentName="PhysicsPileChart" props={physicsPileChartProps} />
    </PageLayout>
  )
}
