import React from "react"
import { Link } from "react-router-dom"

import CodeBlock from "../components/CodeBlock"
import PageLayout from "../components/PageLayout"

// semiotic-bundle-sizes-js:start
// Auto-generated by scripts/sync-bundle-sizes.mjs. Do not edit by hand.
const bundleSizeRows = Object.freeze([
  {
    "importPath": "semiotic/access",
    "kb": 34,
    "blurb": "Chart Access Contract factory and first-wave baseline contracts"
  },
  {
    "importPath": "semiotic/evidence",
    "kb": 46,
    "blurb": "Chart Evidence Envelope, deterministic hashing, and publication gate"
  },
  {
    "importPath": "semiotic/artifact",
    "kb": 118,
    "blurb": "Renderer-independent contracts, claims, time, policy, grounding, and transfer audits"
  },
  {
    "importPath": "semiotic/artifact/react",
    "kb": 4,
    "blurb": "Accessible progressive disclosure for artifact contracts and policy evaluations"
  },
  {
    "importPath": "semiotic/line",
    "kb": 135,
    "blurb": "LineChart only — one-chart micro boundary"
  },
  {
    "importPath": "semiotic/xy",
    "kb": 166,
    "blurb": "LineChart, AreaChart, Scatterplot, Heatmap, + 8 more XY charts"
  },
  {
    "importPath": "semiotic/ordinal",
    "kb": 130,
    "blurb": "BarChart, PieChart, BoxPlot, Histogram, + 11 more categorical charts"
  },
  {
    "importPath": "semiotic/network",
    "kb": 156,
    "blurb": "ForceDirectedGraph, SankeyDiagram, ProcessSankey, Treemap, + 4 more"
  },
  {
    "importPath": "semiotic/geo",
    "kb": 113,
    "blurb": "ChoroplethMap, FlowMap, DistanceCartogram, ProportionalSymbolMap"
  },
  {
    "importPath": "semiotic/realtime",
    "kb": 163,
    "blurb": "RealtimeLineChart, RealtimeHistogram, + 4 streaming charts"
  },
  {
    "importPath": "semiotic/realtime/core",
    "kb": 162,
    "blurb": "Streaming chart types, HOCs, and buffer helpers"
  },
  {
    "importPath": "semiotic/realtime/react",
    "kb": 1,
    "blurb": "Stream status and synced push hooks"
  },
  {
    "importPath": "semiotic/server",
    "kb": 225,
    "blurb": "renderChart, renderDashboard, renderToImage, renderToAnimatedGif"
  },
  {
    "importPath": "semiotic/server/node",
    "kb": 225,
    "blurb": "renderChart, renderDashboard, renderToImage, renderToAnimatedGif"
  },
  {
    "importPath": "semiotic/server/edge",
    "kb": 227,
    "blurb": "renderChart, renderChartWithEvidence, renderToStaticSVG, renderDashboard"
  },
  {
    "importPath": "semiotic/utils",
    "kb": 95,
    "blurb": "ThemeProvider, numeric/accessibility audits, serialization — no chart components"
  },
  {
    "importPath": "semiotic/utils/core",
    "kb": 88,
    "blurb": "Pure theme helpers, numeric/accessibility audits, and serialization"
  },
  {
    "importPath": "semiotic/utils/react",
    "kb": 7,
    "blurb": "ThemeProvider, useTheme, useReducedMotion, useHighContrast, useStreamStatus"
  },
  {
    "importPath": "semiotic/recipes",
    "kb": 99,
    "blurb": "Pure layout functions (waffle, marimekko, flextree, dagre, …)"
  },
  {
    "importPath": "semiotic/recipes/core",
    "kb": 92,
    "blurb": "Pure layout functions (waffle, marimekko, flextree, dagre, …)"
  },
  {
    "importPath": "semiotic/recipes/react",
    "kb": 8,
    "blurb": "Glyph and React layout-selection helpers"
  },
  {
    "importPath": "semiotic/themes",
    "kb": 12,
    "blurb": "Theme presets only (tufte, carbon, etc.)"
  },
  {
    "importPath": "semiotic/themes/core",
    "kb": 12,
    "blurb": "Theme presets and token helpers"
  },
  {
    "importPath": "semiotic/themes/react",
    "kb": 7,
    "blurb": "ThemeProvider/useTheme and hooks"
  },
  {
    "importPath": "semiotic/data",
    "kb": 3,
    "blurb": "bin, rollup, groupBy, pivot, fromVegaLite"
  },
  {
    "importPath": "semiotic/value",
    "kb": 6,
    "blurb": "BigNumber — focal-value KPI / scorecard (SingleValueFrame POC)"
  },
  {
    "importPath": "semiotic/physics",
    "kb": 168,
    "blurb": "GaltonBoardChart, EventDropChart, UnitPileChart, CollisionSwarmChart, PacketFlowChart, PhysicsCustomChart"
  },
  {
    "importPath": "semiotic/physics/matter",
    "kb": 1,
    "blurb": "Matter.js migration helpers + optional peer guard (no chart components)"
  },
  {
    "importPath": "semiotic/physics/rapier",
    "kb": 1,
    "blurb": "Rapier peer guard + adapter decision metadata (no chart components)"
  },
  {
    "importPath": "semiotic/ai",
    "kb": 587,
    "blurb": "All schema-backed charts + validation — optimized for LLM code generation"
  },
  {
    "importPath": "semiotic/ai/core",
    "kb": 135,
    "blurb": "suggestCharts, auditData, describeChart, repairChartConfig, tool adapters — no chart components"
  },
  {
    "importPath": "semiotic/controls",
    "kb": 10,
    "blurb": "DirectManipulationControl, CircularBrush, MobileStandardControls, auditVisualizationControls — no frame renderer"
  },
  {
    "importPath": "semiotic/rough",
    "kb": 3,
    "blurb": "Optional deterministic Rough.js paint backend — exact Semiotic geometry remains authoritative"
  },
  {
    "importPath": "semiotic",
    "kb": 370,
    "blurb": "Everything below (full bundle)"
  }
])
// semiotic-bundle-sizes-js:end

const gettingStartedBundleImports = [
  "semiotic/line",
  "semiotic/xy",
  "semiotic/ordinal",
  "semiotic/network",
  "semiotic/geo",
  "semiotic/realtime",
  "semiotic/server",
  "semiotic/utils",
  "semiotic/themes",
  "semiotic/data",
]

function bundleSizeRow(importPath) {
  const row = bundleSizeRows.find((candidate) => candidate.importPath === importPath)
  if (!row) throw new Error(`Missing generated bundle-size row for ${importPath}`)
  return row
}

const gettingStartedBundleRows = gettingStartedBundleImports.map(bundleSizeRow)

// ---------------------------------------------------------------------------
// Code snippets
// ---------------------------------------------------------------------------

const installSnippet = `npm install semiotic`

const firstChartSnippet = `import { LineChart } from "semiotic/line"

const data = [
  { month: "Jan", sales: 4200 },
  { month: "Feb", sales: 5100 },
  { month: "Mar", sales: 6800 },
  { month: "Apr", sales: 5900 },
  { month: "May", sales: 7200 },
  { month: "Jun", sales: 8100 },
]

function App() {
  return (
    <LineChart
      data={data}
      xAccessor="month"
      yAccessor="sales"
      xLabel="Month"
      yLabel="Sales ($)"
    />
  )
}`

const streamingSnippet = `import { useRef, useEffect } from "react"
import { RealtimeLineChart } from "semiotic/realtime"

function LiveMetrics() {
  const ref = useRef()

  useEffect(() => {
    const ws = new WebSocket("wss://metrics.example.com")
    ws.onmessage = (e) => {
      ref.current?.push(JSON.parse(e.data))
    }
    return () => ws.close()
  }, [])

  return (
    <RealtimeLineChart
      ref={ref}
      timeAccessor="time"
      valueAccessor="latency"
      windowSize={500}
      decay={{ type: "exponential", halfLife: 200 }}
      pulse={{ duration: 300, color: "#22c55e" }}
    />
  )
}`

const pushApiSnippet = `// Any HOC chart supports push via refs — just omit the data prop
const ref = useRef()

// Push from effects, event handlers, or WebSocket callbacks
ref.current?.push({ x: 1, y: 42 })       // single point
ref.current?.pushMany([...points])        // batch
ref.current?.clear()                      // reset

<Scatterplot ref={ref} xAccessor="x" yAccessor="y" />`

const framePropsSnippet = `// Every Chart accepts a frameProps escape hatch
<LineChart
  data={salesData}
  xAccessor="month"
  yAccessor="sales"
  frameProps={{
    annotations: [
      { type: "x", month: "Mar", label: "Q1 End" }
    ],
    hoverAnnotation: true,
    size: [800, 400]
  }}
/>`

// ---------------------------------------------------------------------------
// Styles
// ---------------------------------------------------------------------------

const styles = {
  sectionIntro: {
    fontSize: "18px",
    lineHeight: "1.7",
    color: "var(--text-secondary)",
    marginBottom: "32px",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "16px",
    marginBottom: "32px",
  },
  card: {
    padding: "20px",
    background: "var(--surface-1)",
    border: "1px solid var(--surface-3)",
    borderRadius: "8px",
  },
  cardTitle: {
    margin: "0 0 8px 0",
    fontSize: "16px",
    fontWeight: 600,
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  cardDescription: {
    margin: 0,
    fontSize: "14px",
    lineHeight: "1.6",
    color: "var(--text-secondary)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginBottom: "32px",
    fontSize: "14px",
  },
  th: {
    textAlign: "left",
    padding: "10px 16px",
    borderBottom: "2px solid var(--surface-3)",
    color: "var(--text-secondary)",
    fontWeight: 600,
    fontSize: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  td: {
    padding: "10px 16px",
    borderBottom: "1px solid var(--surface-3)",
    color: "var(--text-primary)",
    lineHeight: "1.5",
  },
  nextStepsList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
    gap: "12px",
  },
  nextStepLink: {
    display: "block",
    padding: "16px 20px",
    background: "var(--surface-1)",
    border: "1px solid var(--surface-3)",
    borderRadius: "8px",
    textDecoration: "none",
    color: "var(--text-primary)",
    fontWeight: 500,
    fontSize: "14px",
    transition: "border-color 0.15s ease, background 0.15s ease",
  },
  nextStepDescription: {
    display: "block",
    marginTop: "4px",
    fontSize: "13px",
    fontWeight: 400,
    color: "var(--text-secondary)",
  },
  note: {
    padding: "12px 16px",
    background: "var(--surface-1)",
    borderLeft: "3px solid var(--accent)",
    borderRadius: "0 8px 8px 0",
    marginBottom: "24px",
    fontSize: "14px",
    lineHeight: "1.6",
    color: "var(--text-secondary)",
  },
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

export default function GettingStartedPage() {
  return (
    <PageLayout
      title="Getting Started"
      breadcrumbs={[{ label: "Getting Started", path: "/getting-started" }]}
      nextPage={{ title: "LineChart", path: "/charts/line-chart" }}
    >
      <p style={styles.sectionIntro}>
        Semiotic is a streaming-first visualization library for React. Every chart is backed by a
        canvas rendering engine with a push API, ring buffer windowing, and visual encodings for
        live data (decay, pulse, staleness). Streaming is optional: pass an array and the same
        pipeline renders a static chart. This guide covers both paths.
      </p>

      {/* --------------------------------------------------------------- */}
      {/* Installation */}
      {/* --------------------------------------------------------------- */}
      <h2 id="installation">Installation</h2>

      <p>Install Semiotic via npm:</p>

      <CodeBlock code={installSnippet} language="bash" />

      <div style={styles.note}>
        <strong>Peer dependencies:</strong> Semiotic requires <strong>React 18+</strong> and{" "}
        <strong>ReactDOM 18+</strong>. Make sure your project already has these installed.
      </div>

      <p>
        Semiotic ships with built-in <strong>TypeScript type definitions</strong>, so no additional{" "}
        <code>@types</code> packages are needed. You get full autocomplete and type checking out of
        the box.
      </p>

      {/* --------------------------------------------------------------- */}
      {/* Your First Chart */}
      {/* --------------------------------------------------------------- */}
      <h2 id="your-first-chart">Your First Chart</h2>

      <p>
        This example renders a line chart of monthly sales. Import <code>LineChart</code>, pass your
        data, and specify which fields map to the x and y axes:
      </p>

      <CodeBlock code={firstChartSnippet} language="jsx" />

      <p>
        Semiotic supplies the axes, scales, hover interactions, and responsive sizing. Props expose
        each of those choices when the defaults no longer fit.
      </p>

      {/* --------------------------------------------------------------- */}
      {/* Streaming Data */}
      {/* --------------------------------------------------------------- */}
      <h2 id="streaming-data">Streaming Data</h2>

      <p>
        Every Semiotic chart uses the same canvas-rendered streaming pipeline. A <code>data</code>{" "}
        array enters the pipeline used for live pushes, with automatic chunking and progressive
        rendering to keep the UI responsive.
      </p>

      <p>
        For live data, use a ref-based push API. Data is microtask-batched (thousands of pushes per
        second coalesce into single render frames) and rendered at 60fps with optional visual
        encodings:
      </p>

      <CodeBlock code={streamingSnippet} language="jsx" />

      <div style={styles.cardGrid}>
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>Decay</h3>
          <p style={styles.cardDescription}>
            Older data fades out. Linear, exponential, or step modes. Per-vertex opacity on lines
            and areas — not just uniform dimming.
          </p>
        </div>
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>Pulse</h3>
          <p style={styles.cardDescription}>
            New data glows briefly. Configurable duration and color. Three visual modes: circle
            glow, rect overlay, and path fill.
          </p>
        </div>
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>Staleness</h3>
          <p style={styles.cardDescription}>
            Charts dim when the feed pauses. Configurable threshold and badge position. Automatic
            recovery when data resumes.
          </p>
        </div>
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>Transitions</h3>
          <p style={styles.cardDescription}>
            Identity-based animation. Nodes matched by stable keys across rebuilds — not array
            index. Respects <code>prefers-reduced-motion</code>.
          </p>
        </div>
      </div>

      <p>
        The push API works on most HOC charts too — not just Realtime* charts. Omit the{" "}
        <code>data</code> prop and push via refs:
      </p>

      <CodeBlock code={pushApiSnippet} language="jsx" />

      {/* --------------------------------------------------------------- */}
      {/* Core Concepts */}
      {/* --------------------------------------------------------------- */}
      <h2 id="core-concepts">Choose the Right Layer</h2>

      <p>
        Start with Charts. Move to Frames or Utilities when the design needs control that the chart
        component does not expose.
      </p>

      <div style={styles.cardGrid}>
        <div style={styles.card}>
          <h3 style={styles.cardTitle}>
            <span className="tier-badge charts">Charts</span>
          </h3>
          <p style={styles.cardDescription}>
            <strong>20 ready-to-use components</strong> like LineChart, BarChart, and Scatterplot.
            Simple props, instant results. This is the best starting point for most visualizations.
          </p>
        </div>

        <div style={styles.card}>
          <h3 style={styles.cardTitle}>
            <span className="tier-badge frames">Frames</span>
          </h3>
          <p style={styles.cardDescription}>
            <strong>
              StreamXYFrame, StreamOrdinalFrame, StreamNetworkFrame, and StreamGeoFrame.
            </strong>{" "}
            Frames expose rendering, interaction, and layout directly. Use one when a Chart keeps a
            decision you need to make for yourself.
          </p>
        </div>

        <div style={styles.card}>
          <h3 style={styles.cardTitle}>
            <span className="tier-badge utilities">Utilities</span>
          </h3>
          <p style={styles.cardDescription}>
            Shared infrastructure like <strong>ThemeProvider</strong>,{" "}
            <strong>ChartContainer</strong>, and <strong>LinkedCharts</strong>. Compose them to
            build coordinated dashboards and themed applications.
          </p>
        </div>
      </div>

      <h3 id="the-frameprops-escape-hatch">The frameProps Escape Hatch</h3>

      <p>
        Every Chart component is built on top of a Frame. When you need advanced functionality that
        a Chart does not directly expose, you can pass additional Frame-level props through the{" "}
        <code>frameProps</code> prop without having to rewrite your entire component:
      </p>

      <CodeBlock code={framePropsSnippet} language="jsx" />

      <p>
        Start with a Chart and customize it as the design develops. If the Chart API becomes the
        constraint, use the underlying Frame directly.
      </p>

      {/* --------------------------------------------------------------- */}
      {/* Choosing the Right Component */}
      {/* --------------------------------------------------------------- */}
      <h2 id="choosing-the-right-component">Choosing the Right Component</h2>

      <p>
        Use this decision matrix to find the right component. Start with your data shape, then pick
        based on what you want to show:
      </p>

      <table style={styles.table}>
        <thead>
          <tr>
            <th style={styles.th}>Data Shape</th>
            <th style={styles.th}>Goal</th>
            <th style={styles.th}>Component</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }} rowSpan={6}>
              Flat array
              <br />
              <code style={{ fontSize: "12px", fontWeight: 400 }}>[{"{x, y}"}]</code>
            </td>
            <td style={styles.td}>Trends over time</td>
            <td style={styles.td}>
              <Link to="/charts/line-chart">LineChart</Link>,{" "}
              <Link to="/charts/area-chart">AreaChart</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Part-to-whole over time</td>
            <td style={styles.td}>
              <Link to="/charts/stacked-area-chart">StackedAreaChart</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Correlations</td>
            <td style={styles.td}>
              <Link to="/charts/scatterplot">Scatterplot</Link>,{" "}
              <Link to="/charts/bubble-chart">BubbleChart</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Compare categories</td>
            <td style={styles.td}>
              <Link to="/charts/bar-chart">BarChart</Link>,{" "}
              <Link to="/charts/dot-plot">DotPlot</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Part-to-whole (categorical)</td>
            <td style={styles.td}>
              <Link to="/charts/stacked-bar-chart">StackedBarChart</Link>,{" "}
              <Link to="/charts/pie-chart">PieChart</Link>,{" "}
              <Link to="/charts/donut-chart">DonutChart</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Distributions</td>
            <td style={styles.td}>
              <Link to="/charts/box-plot">BoxPlot</Link>,{" "}
              <Link to="/charts/swarm-plot">SwarmPlot</Link>
            </td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }} rowSpan={3}>
              Hierarchical
              <br />
              <code style={{ fontSize: "12px", fontWeight: 400 }}>{"{ children: [...] }"}</code>
            </td>
            <td style={styles.td}>Tree/org structure</td>
            <td style={styles.td}>
              <Link to="/charts/tree-diagram">TreeDiagram</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Proportional sizing</td>
            <td style={styles.td}>
              <Link to="/charts/treemap">Treemap</Link>,{" "}
              <Link to="/charts/circle-pack">CirclePack</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Matrix / density</td>
            <td style={styles.td}>
              <Link to="/charts/heatmap">Heatmap</Link>
            </td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }} rowSpan={3}>
              Nodes + edges
              <br />
              <code style={{ fontSize: "12px", fontWeight: 400 }}>
                {"[{id}], [{source, target}]"}
              </code>
            </td>
            <td style={styles.td}>Relationships</td>
            <td style={styles.td}>
              <Link to="/charts/force-directed-graph">ForceDirectedGraph</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Flows and budgets</td>
            <td style={styles.td}>
              <Link to="/charts/sankey-diagram">SankeyDiagram</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Inter-group connections</td>
            <td style={styles.td}>
              <Link to="/charts/chord-diagram">ChordDiagram</Link>
            </td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }} rowSpan={2}>
              Streaming
              <br />
              <code style={{ fontSize: "12px", fontWeight: 400 }}>
                ref.push({"{ time, value }"})
              </code>
            </td>
            <td style={styles.td}>Live trends</td>
            <td style={styles.td}>
              <Link to="/charts/realtime-line-chart">RealtimeLineChart</Link>
            </td>
          </tr>
          <tr>
            <td style={styles.td}>Live aggregates</td>
            <td style={styles.td}>
              <Link to="/charts/realtime-histogram">RealtimeHistogram</Link>,{" "}
              <Link to="/charts/realtime-swarm-chart">RealtimeSwarmChart</Link>
            </td>
          </tr>
        </tbody>
      </table>

      <h3 id="chart-vs-frame">Chart vs Frame: When to Graduate</h3>

      <table style={styles.table}>
        <thead>
          <tr>
            <th style={styles.th}></th>
            <th style={{ ...styles.th, color: "var(--tier-charts, #22c55e)" }}>Chart</th>
            <th style={{ ...styles.th, color: "var(--tier-frames, #a855f7)" }}>Frame</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Lines of code</td>
            <td style={styles.td}>5-15</td>
            <td style={styles.td}>20-80+</td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Custom marks</td>
            <td style={styles.td}>No</td>
            <td style={styles.td}>Yes</td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Annotations</td>
            <td style={styles.td}>
              Via <code>frameProps</code>
            </td>
            <td style={styles.td}>Direct prop</td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Custom tooltips</td>
            <td style={styles.td}>Yes</td>
            <td style={styles.td}>Yes</td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Custom rendering</td>
            <td style={styles.td}>No</td>
            <td style={styles.td}>Full SVG/Canvas control</td>
          </tr>
          <tr>
            <td style={{ ...styles.td, fontWeight: 600 }}>Best for</td>
            <td style={styles.td}>Standard charts, dashboards, quick prototypes</td>
            <td style={styles.td}>Bespoke visualizations, novel encodings</td>
          </tr>
        </tbody>
      </table>

      <div style={styles.note}>
        <strong>Tip:</strong> Start with a Chart. Use <code>frameProps</code> for one-off
        customizations. Reach for a Frame when you need to control the marks, layout, or rendering.
      </div>

      {/* --------------------------------------------------------------- */}
      {/* Bundle Size */}
      {/* --------------------------------------------------------------- */}
      <h2 id="bundle-size">Bundle Size</h2>

      <p>
        Semiotic ships <strong>{bundleSizeRows.length} stable JavaScript entry points</strong> so
        you can choose the smallest public boundary that fits the route. Don't import from{" "}
        <code>"semiotic"</code> unless you need everything — use the sub-path that matches your
        chart category:
      </p>

      <CodeBlock
        code={`// Instead of this (${bundleSizeRow("semiotic").kb} KB first-party gzip — full library):
import { LineChart } from "semiotic"

// Do this (${bundleSizeRow("semiotic/line").kb} KB first-party gzip — LineChart boundary):
import { LineChart } from "semiotic/line"

// Or this (${bundleSizeRow("semiotic/xy").kb} KB first-party gzip — all XY charts):
import { LineChart } from "semiotic/xy"

// Or this (${bundleSizeRow("semiotic/ordinal").kb} KB first-party gzip — categorical charts):
import { BarChart } from "semiotic/ordinal"

// Mixing is fine — shared runtime is deduplicated:
import { LineChart } from "semiotic/line"
import { BarChart } from "semiotic/ordinal"`}
        language="js"
      />

      <table style={{ ...styles.table, marginTop: "16px" }}>
        <thead>
          <tr style={styles.headerRow}>
            <th style={styles.th}>Entry Point</th>
            <th style={styles.th}>gzip</th>
            <th style={styles.th}>Charts</th>
          </tr>
        </thead>
        <tbody>
          {gettingStartedBundleRows.map((row) => (
            <tr key={row.importPath}>
              <td style={{ ...styles.td, fontFamily: "monospace", fontSize: "13px" }}>
                {row.importPath}
              </td>
              <td style={styles.td}>{row.kb} KB</td>
              <td style={styles.td}>{row.blurb}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div style={styles.note}>
        <strong>How to read these numbers:</strong> They measure Semiotic's generated first-party
        artifacts, not a complete application bundle. Shared runtime and dependencies are
        deduplicated by modern bundlers; consult the checked cold-consumer table in the README
        before making a route-level size decision.
      </div>

      {/* --------------------------------------------------------------- */}
      {/* Next Steps */}
      {/* --------------------------------------------------------------- */}
      <h2 id="next-steps">Next Steps</h2>

      <p>Now that you have the basics, dive into the component documentation:</p>

      <ul style={styles.nextStepsList}>
        <li>
          <Link to="/charts/line-chart" style={styles.nextStepLink}>
            LineChart
            <span style={styles.nextStepDescription}>
              Trends, time series, and multi-line comparisons
            </span>
          </Link>
        </li>
        <li>
          <Link to="/charts/realtime-line-chart" style={styles.nextStepLink}>
            RealtimeLineChart
            <span style={styles.nextStepDescription}>
              Live streaming data with decay and pulse encoding
            </span>
          </Link>
        </li>
        <li>
          <Link to="/features/realtime-encoding" style={styles.nextStepLink}>
            Streaming Encodings
            <span style={styles.nextStepDescription}>
              Decay, pulse, staleness, and transitions in depth
            </span>
          </Link>
        </li>
        <li>
          <Link to="/charts/bar-chart" style={styles.nextStepLink}>
            BarChart
            <span style={styles.nextStepDescription}>
              Categorical comparisons, grouped and stacked bars
            </span>
          </Link>
        </li>
      </ul>
    </PageLayout>
  )
}
