import { expect, test, type Page } from "@playwright/test"

const retainedTable = (page: Page) => page.getByRole("table", { name: "Records currently retained by the chart" })
const renderedCanvas = (page: Page) => page.getByTestId("live-chart-rendering").locator("canvas[aria-label]")
const pixels = (page: Page) => renderedCanvas(page).evaluate((canvas: HTMLCanvasElement) =>
  new Promise<string>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve(canvas.toDataURL())))),
)

test("live corrections paint, retention stays bounded and reconnect recovers the current source window", async ({ page }) => {
  await page.goto("/tasks/update-live-chart")
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0118", "obs-0309:0215"])
  await expect(renderedCanvas(page)).toHaveAttribute("aria-label", /3 points, 1 lines/)
  const initialPixels = await pixels(page)
  await page.getByRole("button", { name: "Advance source" }).click()
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0114", "obs-0309:0215"])
  await expect.poll(() => pixels(page)).not.toBe(initialPixels)
  const correctedPixels = await pixels(page)
  await page.getByRole("button", { name: "Advance source" }).click()
  await page.getByRole("button", { name: "Advance source" }).click()
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0209:0114", "obs-0309:0215", "obs-0409:0320", "obs-0509:0416"])
  await expect(renderedCanvas(page)).toHaveAttribute("aria-label", /4 points, 1 lines/)
  await expect.poll(() => pixels(page)).not.toBe(correctedPixels)
  const connectedPixels = await pixels(page)
  await page.getByRole("button", { name: "Disconnect" }).click()
  await page.getByRole("button", { name: "Advance source" }).click()
  await page.getByRole("button", { name: "Advance source" }).click()
  await expect(page.getByTestId("live-chart-status")).toContainText("2 unapplied events")
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0209:0114", "obs-0309:0215", "obs-0409:0320", "obs-0509:0416"])
  expect(await pixels(page)).toBe(connectedPixels)
  await page.getByRole("button", { name: "Reconnect" }).click()
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0309:0217", "obs-0409:0320", "obs-0509:0416", "obs-0609:0519"])
  await expect.poll(() => pixels(page)).not.toBe(connectedPixels)
  await expect(renderedCanvas(page)).toHaveAttribute("aria-label", /4 points, 1 lines/)
  await page.getByRole("button", { name: "Restart fixture" }).click()
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0118", "obs-0309:0215"])
  await expect(renderedCanvas(page)).toHaveAttribute("aria-label", /3 points, 1 lines/)
})

test("replay pauses without losing records and restart cancels the previous session's timer", async ({ page }) => {
  await page.clock.install()
  await page.goto("/tasks/update-live-chart")
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0118", "obs-0309:0215"])
  await page.getByRole("button", { name: "Play replay" }).click()
  await page.clock.runFor(1_100)
  await expect(page.getByTestId("live-chart-status")).toContainText("Source event 1 of 5")
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0114", "obs-0309:0215"])
  await page.getByRole("button", { name: "Pause replay" }).click()
  await page.clock.runFor(2_000)
  await expect(page.getByTestId("live-chart-status")).toContainText("Source event 1 of 5")
  await page.getByRole("button", { name: "Play replay" }).click()
  await page.getByRole("button", { name: "Restart fixture" }).click()
  await page.clock.runFor(2_000)
  await expect(page.getByTestId("live-chart-status")).toContainText("Source event 0 of 5")
  await expect(retainedTable(page).locator("tbody tr")).toHaveText(["obs-0109:0012", "obs-0209:0118", "obs-0309:0215"])
})
